//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DummyTag
    {
        public string C_TagName_ { get; set; }
        public string C_Average_ { get; set; }
        public string C_Time_ { get; set; }
        public int newcolumn { get; set; }
    }
}
